### ISSUE TITLE
[Bug] Slices aren't being recorded

### ISSUE THREAD

**Issue by farazfazli** [remychantenay/slog-otel#7]
Hi,

First of all - wanted to thank you for making a great library. I am reaching out because while using this library, I noticed a small bug. When I have a slice of `string` or `any` in an argument, it doesn't get recorded.

Example:
```go
strs := make([]string, 2)
strs = append(strs, "arg1")
strs = append(strs, "arg2")
slog.InfoContext(ctx, "arguments", "strs", strs)
```

This shows up fine on my log output with the appropriate `trace_id` and `span_id`. However, the argument doesn't get recorded with OTel and is missing from the resulting trace. My configuration is the same as the usage example:
```go
slog.SetDefault(slog.New(slogotel.OtelHandler{
    Next: slog.NewJSONHandler(os.Stdout, nil),
}))
```

First, I thought that this might be a bug on the receiver side, but then I switched to using `stdouttrace` and still noticed that it isn't getting recorded. If I marshal the array into a JSON string and then log it with slog, it works fine and shows up in the trace. Are you able to replicate this from your end?

Thanks,
Faraz

**Comment by remychantenay** [comment]
Hey @farazfazli 

Thanks a lot for sharing and spending time on this. I believe #8 will fix this 👍

**Comment by farazfazli** [comment]
Thank you @remychantenay, it's working great now
